import type { Site } from './types.js';

export const sampleSites: Site[] = [
	// 置顶推荐网站
	{
		title: 'GitHub',
		url: 'https://github.com',
		favicon: 'https://github.com/favicon.ico',
		description: '全球领先的软件开发平台',
		category: '开发工具',
		tags: ['code', 'developer', 'social', 'git'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: true,
		supportsPWA: true,
		supportsHTTPS: true,
		recommendation: '开发者必备平台',
		createdAt: '2025-07-06T12:00:00Z'
	},
	{
		title: 'Stack Overflow',
		url: 'https://stackoverflow.com',
		favicon: 'https://stackoverflow.com/favicon.ico',
		description: '程序员问答社区',
		category: '开发工具',
		tags: ['programming', 'qa', 'community'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '解决编程问题的好地方',
		createdAt: '2025-07-06T12:01:00Z'
	},
	// 搜索引擎
	{
		title: 'Google',
		url: 'https://google.com',
		favicon: 'https://www.google.com/favicon.ico',
		description: '全球最大的搜索引擎',
		category: '搜索引擎',
		tags: ['search', 'engine'],
		ageRating: 'SFW',
		language: 'zh-CN',
		starred: false,
		supportsPWA: true,
		supportsHTTPS: true,
		recommendation: '最受欢迎的搜索引擎',
		createdAt: '2025-07-06T12:02:00Z'
	},
	{
		title: 'Baidu 百度',
		url: 'https://baidu.com',
		favicon: 'https://www.baidu.com/favicon.ico',
		description: '全球最大的中文搜索引擎',
		category: '搜索引擎',
		tags: ['search', 'engine', 'china'],
		ageRating: 'SFW',
		language: 'zh-CN',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '中文搜索首选',
		createdAt: '2025-07-06T12:03:00Z'
	},
	{
		title: 'DuckDuckGo',
		url: 'https://duckduckgo.com',
		favicon: 'https://duckduckgo.com/favicon.ico',
		description: '注重隐私的搜索引擎',
		category: '搜索引擎',
		tags: ['search', 'privacy', 'secure'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '保护隐私的搜索选择',
		createdAt: '2025-07-06T12:04:00Z'
	},
	{
		title: 'PornHub',
		url: 'https://pornhub.com',
		favicon: 'https://pornhub.com/favicon.ico',
		description: '成人内容网站',
		category: '娱乐',
		tags: ['porn', 'adult', '18+'],
		ageRating: '18+',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '成人内容网站',
		createdAt: '2025-07-06T12:05:00Z'
	},
	{
		title: 'Bilibili',
		url: 'https://bilibili.com',
		favicon: 'https://bilibili.com/favicon.ico',
		description: '弹幕视频网站',
		category: '娱乐',
		tags: ['video', 'anime', 'chinese'],
		ageRating: 'SFW',
		language: 'zh-CN',
		starred: true,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '弹幕视频网站',
		createdAt: '2025-07-06T12:06:00Z'
	},

	// 再添加 10 个测试数据
	{
		title: 'YouTube',
		url: 'https://youtube.com',
		favicon: 'https://youtube.com/favicon.ico',
		description: '视频分享平台',
		category: '娱乐',
		tags: ['video', 'social', 'google'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: true,
		supportsHTTPS: true,
		recommendation: '全球最大的视频分享平台',
		createdAt: '2025-07-06T12:07:00Z'
	},
	{
		title: 'Twitter',
		url: 'https://twitter.com',
		favicon: 'https://twitter.com/favicon.ico',
		description: '社交媒体平台',
		category: '社交媒体',
		tags: ['social', 'microblogging'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '实时信息分享平台',
		createdAt: '2025-07-06T12:08:00Z'
	},
	{
		title: 'Facebook',
		url: 'https://facebook.com',
		favicon: 'https://facebook.com/favicon.ico',
		description: '社交媒体平台',
		category: '社交媒体',
		tags: ['social', 'newsfeed'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '连接世界的平台',
		createdAt: '2025-07-06T12:09:00Z'
	},
	{
		title: 'Instagram',
		url: 'https://instagram.com',
		favicon: 'https://instagram.com/favicon.ico',
		description: '图片分享平台',
		category: '社交媒体',
		tags: ['social', 'photo', 'stories'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '发现美好世界的窗口',
		createdAt: '2025-07-06T12:10:00Z'
	},
	{
		title: 'TikTok',
		url: 'https://tiktok.com',
		favicon: 'https://tiktok.com/favicon.ico',
		description: '短视频分享平台',
		category: '社交媒体',
		tags: ['social', 'video', 'shorts'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '年轻人的天堂',
		createdAt: '2025-07-06T12:11:00Z'
	},
	{
		title: 'LinkedIn',
		url: 'https://linkedin.com',
		favicon: 'https://linkedin.com/favicon.ico',
		description: '职业社交平台',
		category: '社交媒体',
		tags: ['social', 'professional', 'networking'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '职场人的首选',
		createdAt: '2025-07-06T12:12:00Z'
	},
	{
		title: 'Pinterest',
		url: 'https://pinterest.com',
		favicon: 'https://pinterest.com/favicon.ico',
		description: '图片收藏和分享平台',
		category: '社交媒体',
		tags: ['social', 'photo', 'board'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '发现灵感的宝库',
		createdAt: '2025-07-06T12:13:00Z'
	},
	{
		title: 'Reddit',
		url: 'https://reddit.com',
		favicon: 'https://reddit.com/favicon.ico',
		description: '在线论坛和社区',
		category: '社交媒体',
		tags: ['social', 'forum', 'discussion'],
		ageRating: 'SFW',
		language: 'en-US',
		starred: false,
		supportsPWA: false,
		supportsHTTPS: true,
		recommendation: '无尽的讨论与分享',
		createdAt: '2025-07-06T12:14:00Z'
	}
];